<?php echo $this->doctype(); ?>

<html lang="en">
    <head>
        <meta charset="utf-8">
        <?php echo $this->headTitle('ZF2 '. $this->translate('Skeleton Application'))->setSeparator(' - ')->setAutoEscape(false) ?>

        <?php echo $this->headMeta()->appendName('viewport', 'width=device-width, initial-scale=1.0') ?>

        <!-- Le styles -->
        <?php echo $this->headLink(array('rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon', 'href' => $this->basePath() . '/images/favicon.ico'))
                        ->prependStylesheet($this->basePath() . '/css/bootstrap-responsive.min.css')
                        ->prependStylesheet($this->basePath() . '/css/style.css')
                        ->prependStylesheet($this->basePath() . '/css/bootstrap.min.css') ?>

        <!-- Scripts -->
        <?php echo $this->headScript()->prependFile($this->basePath() . '/js/modules/plugins/nav.js')
        							  ->prependFile($this->basePath() . '/js/modules/utils/namespace.js')
        							  
        							  ->prependFile($this->basePath() . '/js/vendors/console.log.js')
        							  ->prependFile($this->basePath() . '/js/vendors/modules/html5/vpre3.6/html5.js', 'text/javascript', array('conditional' => 'lt IE 9',))
                                      ->prependFile($this->basePath() . '/js/vendors/modules/bootstrap/bootstrap.min.js')
                                      ->prependFile($this->basePath() . '/js/vendors/modules/jquery/1.8.2/jquery.min.js')
                                       ?>
    </head>
    <body>
        <div class="navbar navbar-inverse navbar-fixed-top">
            <div class="navbar-inner">
                <div class="container">
                    <a class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse">
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                    </a>
                    <a class="brand" href="<?php echo $this->url('home') ?>"><?php echo $this->translate('Skeleton Application') ?></a>
                    <div class="nav-collapse collapse">
                        <ul class="nav">
                            <li class="home active"><a href="<?php echo $this->url('home') ?>"><?php echo $this->translate('Home') ?></a></li>
			    			<li class="album"><a href="<?php echo $this->url('album') ?>"><?php echo $this->translate('Album') ?></a></li>
                            <li class="album-orm"><a href="<?php echo $this->url('album-orm') ?>"><?php echo $this->translate('AlbumORM') ?></a></li>
                            <li class="album-orm-annotation"><a href="<?php echo $this->url('album-orm-annotation') ?>"><?php echo $this->translate('AlbumORMAnnotation') ?></a></li>                        
                        	<li class="album-memcache"><a href="<?php echo $this->url('album-memcache') ?>"><?php echo $this->translate('AlbumMemcache') ?></a></li>                        
                        </ul>
                    </div><!--/.nav-collapse -->
                </div>
            </div>
        </div>
        <div class="container">
            <?php echo $this->content; ?>
            <hr>
            <footer>
                
            </footer>
        </div> <!-- /container -->
        <?php echo $this->inlineScript() ?>
    </body>
</html>
